# Generated by Django 5.1.4 on 2024-12-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(related_name='groups', to='students.student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='teachers.teacher')),
            ],
        ),
    ]
